### ISSUE TITLE
Grid szinezés

### ISSUE THREAD

**Issue by jviktor82** [programozas-kft/Zeusz-Desktop#3]
Ha nem megfelelő a partnerek neve, illetve hiányzik az adószám, akkor egy hatalmas üzenet helyett jó lenne, ha inkább a táblázat háttere színeződne a problémának megfelelően. (áttekinthetőbb, könnyebben kezelhetőbb is)

**Comment by programozas** [comment]
Az adóraktár program adószám nélkül nem enged felvenni vevőt, ez kötelező mező. Egyébként nem adóraktár esetén is kötelező mezőként kezeljük, kivéve ha vevő típusa magánszemélynek van állítva. A névmegadásban viszont bevezetem hogy xml kompatibilis karaktereket engedjen csak. Ezekután kíváncsi leszek hogy ezeket majd hogy kezeli a NAV online rendszere mert pont tegnap volt egy olyen ügyfelem akinek a vevő neve nem az autentikált név volt és kidobta a rendszer hogy nem megfelelő név és adószám páros. Programozóként én támogatom a dedikált naprakész cégnév és adószám páros táblázat központi megjelentetését.

**Comment by programozas** [comment]
Errorból messageboxra programoztam...
